import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
export async function verifySessionList({ send, evaluate, baseUrl, benchDirectory }) {
  const checks = [];
  const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
  const check = (name, value) => { assert.ok(value, name); checks.push(name); console.log('PASS ' + name); };
  const waitFor = async expression => {
    for (let attempt = 0; attempt < 150; attempt++) {
      if (await evaluate(expression)) return;
      await delay(40);
    }
    throw new Error('Timed out: ' + expression);
  };
  const openFixture = async parameters => {
    const fixtureRunId = randomUUID();
    await send('Page.navigate', { url: baseUrl + '/?' + parameters + '&fixtureRunId=' + fixtureRunId });
    await waitFor('window.benchmark?.fixtureRunId === ' + JSON.stringify(fixtureRunId) + ' && !!benchmark.metrics.initialSnapshot');
    await delay(400);
  };
  await openFixture('count=500&leadingHeight=1400');
  check('an offscreen session list keeps only a small mounted range', await evaluate('benchmark.cards().length <= 2'));
  await evaluate('benchmark.measure(() => window.fixtureSetLeadingHeight(0))');
  await delay(200);
  check('collapsing an earlier section refreshes the visible range without scrolling', await evaluate('document.querySelector("main").scrollTop === 0 && benchmark.cards().some(card => card.getBoundingClientRect().bottom >= 900)'));
  await openFixture('count=5000');
  check('5000 sessions keep fewer than 40 mounted cards', await evaluate('benchmark.cards().length > 0 && benchmark.cards().length < 40'));
  await evaluate('benchmark.measure(() => benchmark.findButton("sessionManager.select").click())');
  await evaluate('benchmark.measure(() => benchmark.findButton("sessionManager.selectLoaded").click())');
  check('select all includes all 5000 loaded sessions', await evaluate('!!benchmark.findButton("sessionManager.bulkDelete", {count:5000})'));
  check('visible checkboxes are checked after select all', await evaluate('benchmark.cards().every(card=>card.querySelector("input[type=checkbox]").checked)'));
  await evaluate('benchmark.scroll(90)');
  check('scroll reaches session 4999 without mounting the full list', await evaluate('benchmark.cards().length < 40 && benchmark.cards().at(-1).textContent.includes("Session 4999")'));
  await evaluate('benchmark.measure(() => benchmark.cards().at(-1).querySelector("input[type=checkbox]").click())');
  check('deselecting the last session preserves the remaining 4999 selections', await evaluate('!!benchmark.findButton("sessionManager.bulkDelete", {count:4999})'));
  await evaluate('benchmark.measure(() => { document.querySelector("main").scrollTop=0; })');
  check('selection survives rows leaving and re-entering the viewport', await evaluate('benchmark.cards()[0].querySelector("input[type=checkbox]").checked'));
  await evaluate('benchmark.measure(() => benchmark.findButton("sessionManager.cancelSelection").click())');
  await evaluate('(async()=>{document.querySelector("main").scrollTop=180000; await benchmark.nextPaint(); await benchmark.nextPaint();})()');
  const previousScrollTop = await evaluate('document.querySelector("main").scrollTop');
  await evaluate('benchmark.measure(() => benchmark.cards().find(card=>{ const rect=card.getBoundingClientRect();return rect.top>50 && rect.bottom<850; }).querySelector("button").click())');
  await waitFor('!!document.getElementById("back")');
  await evaluate('benchmark.measure(() => document.getElementById("back").click())');
  await delay(150);
  const restoredScrollTop = await evaluate('document.querySelector("main").scrollTop');
  check('returning from detail restores the main scroll position', Math.abs(previousScrollTop-restoredScrollTop)<2);
  check('returning from detail restores visible virtual rows', await evaluate('benchmark.cards().some(card=>{const rect=card.getBoundingClientRect();return rect.top<900 && rect.bottom>0;})'));
  await evaluate('benchmark.navigate("/empty")');
  await delay(100);
  await evaluate('benchmark.navigate("/coding/codex")');
  check('KeepAlive tab return leaves the list visible', await evaluate('benchmark.cards().some(card=>{const rect=card.getBoundingClientRect();return rect.top<900 && rect.bottom>0;})'));
  await evaluate('benchmark.setInput("session-004999")');
  await waitFor('benchmark.metrics.expectedTotal === 1 && benchmark.cards().length === 1');
  check('exact session id search finds an initially unmounted session', await evaluate('benchmark.cards()[0].textContent.includes("Session 4999")'));
  check('filtering a scrolled list keeps the result inside the viewport', await evaluate('benchmark.cards()[0].getBoundingClientRect().top < 900 && benchmark.cards()[0].getBoundingClientRect().bottom > 0'));
  await evaluate('benchmark.setInput("")');
  await waitFor('benchmark.metrics.expectedTotal === 5000 && benchmark.cards().length > 1');
  await delay(80);
  const requestsBeforeSourceSwitch = await evaluate('benchmark.metrics.requests.length');
  await evaluate('benchmark.measure(() => Array.from(document.querySelectorAll("[role=tab]")).find(node=>node.textContent==="本机").click())');
  check('local source filtering uses the complete loaded snapshot', await evaluate('document.body.textContent.includes("2500") && benchmark.cards().length < 40'));
  await evaluate('benchmark.measure(() => Array.from(document.querySelectorAll("[role=tab]")).find(node=>node.textContent==="全部").click())');
  check('source switching reuses the snapshot without another backend list call', (await evaluate('benchmark.metrics.requests.length')) === requestsBeforeSourceSwitch);
  await evaluate('benchmark.measure(() => benchmark.findButton("sessionManager.select").click())');
  await evaluate('benchmark.measure(() => benchmark.findButton("sessionManager.selectLoaded").click())');
  await evaluate('benchmark.setInput("session-004999")');
  await waitFor('benchmark.metrics.expectedTotal === 1 && benchmark.cards().length === 1');
  check('search clears previous selection rather than retaining invisible sessions', await evaluate('!benchmark.cards()[0].querySelector("input[type=checkbox]").checked && !!benchmark.findButton("sessionManager.bulkDelete",{count:0})'));
  await evaluate('benchmark.setInput("no-session-matches-this-query")');
  await waitFor('benchmark.metrics.expectedTotal === 0 && benchmark.cards().length === 0');
  check('empty search results display an empty state', await evaluate('!!document.querySelector(".ant-empty")'));
  await openFixture('count=500');
  check('missing resume commands keep the copy action disabled', await evaluate('benchmark.cards()[0].querySelectorAll("button")[1].disabled'));
  await evaluate('benchmark.cards()[1].querySelectorAll("button")[1].click()');
  check('copying resume commands uses the selected session', await evaluate('window.fixtureCopiedText === benchmark.sessions[1].resumeCommand'));
  await evaluate('benchmark.cards()[1].querySelector("button").focus()');
  check('session titles accept keyboard focus', await evaluate('document.activeElement === benchmark.cards()[1].querySelector("button")'));
  await send('Input.dispatchKeyEvent', { type: 'keyDown', key: 'Enter', code: 'Enter', text: '\r', unmodifiedText: '\r', windowsVirtualKeyCode: 13 });
  await send('Input.dispatchKeyEvent', { type: 'keyUp', key: 'Enter', code: 'Enter', windowsVirtualKeyCode: 13 });
  await waitFor('!!document.getElementById("back")');
  check('keyboard activation opens the session detail', true);
  await evaluate('benchmark.measure(() => document.getElementById("back").click())');
  await evaluate('benchmark.measure(() => benchmark.findButton("sessionManager.select").click())');
  await evaluate('benchmark.measure(() => {benchmark.cards()[0].querySelector("input[type=checkbox]").click();benchmark.cards()[1].querySelector("input[type=checkbox]").click();})');
  await evaluate('window.fixtureFailDelete = benchmark.sessions[1].sourcePath; benchmark.findButton("sessionManager.bulkDelete",{count:2}).click()');
  await waitFor('!!document.querySelector(".ant-modal-confirm")');
  await evaluate('Array.from(document.querySelectorAll(".ant-modal-confirm button")).find(button=>button.textContent.replace(/\\s/g,"")==="删除").click()');
  await waitFor('benchmark.metrics.expectedTotal === 499 && !!benchmark.findButton("sessionManager.bulkDelete",{count:1})');
  check('partial deletion refreshes the list and preserves only the failed selection', await evaluate('benchmark.cards()[0].textContent.includes("Session 1 ") && benchmark.cards()[0].querySelector("input[type=checkbox]").checked && !benchmark.cards()[1].querySelector("input[type=checkbox]").checked'));
  await openFixture('count=500&long=1');
  await send('Emulation.setDeviceMetricsOverride', { width:600,height:800,deviceScaleFactor:1,mobile:false });
  await delay(600);
  const geometry = await evaluate('benchmark.cards().map(card=>{const rect=card.getBoundingClientRect();return {top:rect.top,bottom:rect.bottom,left:rect.left,right:rect.right,height:rect.height};})');
  check('wrapped long paths create measured variable-height rows', new Set(geometry.map(row=>row.height)).size>1);
  check('variable-height rows do not overlap', geometry.every((row,index)=>index===0 || row.top>=geometry[index-1].bottom));
  check('long paths stay within the narrow viewport', geometry.every(row=>row.left>=0 && row.right<=600));
  await evaluate('benchmark.scroll(90)');
  await evaluate('(async()=>{for(let i=0;i<5;i++){document.querySelector("main").scrollTop=document.querySelector("main").scrollHeight;await benchmark.nextPaint();}})()');
  check('variable-height scrolling reaches the last session', await evaluate('benchmark.cards().at(-1).textContent.includes("Session 499")'));
  await evaluate('benchmark.measure(()=>{document.querySelector("main").scrollTop=0;})');
  await delay(200);
  for (const mode of ['light','dark','system']) {
    if(mode==='system') await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-color-scheme',value:'dark'}]});
    await evaluate('benchmark.setTheme(' + JSON.stringify(mode) + ')');
    await delay(200);
    const colors=await evaluate('({theme:document.documentElement.dataset.theme,background:getComputedStyle(benchmark.cards()[0]).backgroundColor,text:getComputedStyle(benchmark.cards()[0].querySelector("button")).color})');
    check(mode+' theme keeps token-based text and surface colors distinct',colors.background!==colors.text && colors.theme===(mode==='light'?'light':'dark'));
    const screenshot=await send('Page.captureScreenshot',{format:'png'});
    await writeFile(path.join(benchDirectory,'session-list-'+mode+'.png'),Buffer.from(screenshot.data,'base64'));
  }
  await send('Emulation.setDeviceMetricsOverride', { width:1280,height:900,deviceScaleFactor:1,mobile:false });
  await openFixture('count=2000&recent=1&tool=opencode');
  await waitFor('benchmark.metrics.expectedTotal===2000');
  check('recent snapshot is replaced by a complete OpenCode list without pagination', await evaluate('benchmark.metrics.requests.filter(item=>item.command==="list_tool_sessions").map(item=>item.args.loadMode).join(",")==="cache-first,full" && benchmark.cards().length<40'));
  // Codex project-less chat residue cleanup (issue #400).
  const confirmDeleteButton = 'Array.from(document.querySelectorAll(".ant-modal-confirm button")).find(button=>button.textContent.replace(/\\s/g,"")==="删除")';
  const deleteButtonOf = index => 'benchmark.cards()[' + index + '].querySelectorAll("button")[2]';

  await openFixture('count=20');
  const plainHeader = await evaluate('benchmark.panelHeaderGeometry()');
  check('the session search bar keeps its sticky offset', plainHeader.toolbarTop === '48px' && plainHeader.headerHeight > 0 && plainHeader.headerHeight <= 60);
  await openFixture('count=20&extra=1');
  const wideHeader = await evaluate('benchmark.panelHeaderGeometry()');
  check('an extra header action does not change the header height', wideHeader.headerHeight === plainHeader.headerHeight && wideHeader.extraRows === plainHeader.extraRows && wideHeader.toolbarTop === plainHeader.toolbarTop);
  await send('Emulation.setDeviceMetricsOverride', { width:700,height:800,deviceScaleFactor:1,mobile:false });
  await delay(400);
  const narrowHeader = await evaluate('benchmark.panelHeaderGeometry()');
  check('header actions stay on one row at a narrow width', narrowHeader.extraRows === plainHeader.extraRows && narrowHeader.extraHeight <= plainHeader.extraHeight);
  await send('Emulation.setDeviceMetricsOverride', { width:1280,height:900,deviceScaleFactor:1,mobile:false });
  await delay(200);

  await evaluate('benchmark.measure(()=>' + deleteButtonOf(0) + '.click())');
  await waitFor('!!benchmark.confirmDialog()');
  const emptyWorkspaceDialog = await evaluate('benchmark.confirmDialog()');
  check('delete confirmation offers both Codex cleanup actions', emptyWorkspaceDialog.checkboxStates.length === 2);
  check('an empty workspace and its trust entry are preselected', emptyWorkspaceDialog.checkboxStates.every(Boolean));
  check('cleanup options render inside the confirmation without overflow', !emptyWorkspaceDialog.contentOverflows && emptyWorkspaceDialog.widestLineFitsModal);
  check('confirmation footer stays inside the viewport', emptyWorkspaceDialog.footerInViewport);
  check('cleanup labels describe the workspace and the trust entry', emptyWorkspaceDialog.checkboxLabels.some(label=>label.includes('Documents\\Codex') && label.includes('信任配置')));
  await evaluate('benchmark.measure(()=>' + confirmDeleteButton + '.click())');
  await waitFor('benchmark.metrics.requests.some(item=>item.command==="delete_tool_session")');
  check('pressing delete carries both cleanup choices to the backend', await evaluate('(()=>{const request=benchmark.metrics.requests.filter(item=>item.command==="delete_tool_session").at(-1);return request.args.cleanup.removeWorkspace===true && request.args.cleanup.removeTrustEntry===true;})()'));

  await openFixture('count=20');
  await evaluate('benchmark.measure(()=>benchmark.findButton("sessionManager.select").click())');
  await evaluate('benchmark.measure(()=>{benchmark.cards()[0].querySelector("input[type=checkbox]").click();benchmark.cards()[1].querySelector("input[type=checkbox]").click();})');
  await evaluate('benchmark.measure(()=>benchmark.findButton("sessionManager.bulkDelete",{count:2}).click())');
  await waitFor('!!benchmark.confirmDialog()');
  const mixedDialog = await evaluate('benchmark.confirmDialog()');
  check('a bulk selection with a non-empty workspace is not preselected for removal', mixedDialog.checkboxStates[0] === false);
  check('bulk confirmation still preselects the trust entries', mixedDialog.checkboxStates[1] === true);
  await evaluate('benchmark.measure(()=>document.querySelectorAll(".ant-modal-confirm input[type=checkbox]")[0].click())');
  await evaluate('benchmark.measure(()=>' + confirmDeleteButton + '.click())');
  await waitFor('benchmark.metrics.requests.some(item=>item.command==="delete_tool_sessions")');
  check('the bulk delete carries the confirmed cleanup choice', await evaluate('(()=>{const request=benchmark.metrics.requests.filter(item=>item.command==="delete_tool_sessions").at(-1);return request.args.cleanup.removeWorkspace===true && request.args.cleanup.removeTrustEntry===true;})()'));
  check('bulk deletion still reports its own count', await evaluate('benchmark.metrics.expectedTotal===18'));

  // The standalone Codex residue dialog.
  await openFixture('count=5');
  await evaluate('benchmark.navigate("/codex-residue")');
  await waitFor('!!document.querySelector(".ant-modal")');
  await delay(300);
  const residueDialog = await evaluate(`(()=>{const modal=document.querySelector('.ant-modal');const boxes=Array.from(modal.querySelectorAll('input[type=checkbox]'));const groups=Array.from(modal.querySelectorAll('section')).map(node=>node.textContent.slice(0,18));const container=modal.querySelector('.ant-modal-container');const limit=container.getBoundingClientRect();return{checked:boxes.map(node=>node.checked),disabled:boxes.map(node=>node.disabled),groups,bodyOverflows:modal.querySelector('.ant-modal-body').scrollWidth>modal.querySelector('.ant-modal-body').clientWidth+1,insideModal:Array.from(modal.querySelectorAll('[class*="item"]')).every(node=>{const rect=node.getBoundingClientRect();return rect.left>=limit.left-1&&rect.right<=limit.right+1;}),footerInViewport:Array.from(modal.querySelectorAll('.ant-modal-footer button')).every(button=>button.getBoundingClientRect().bottom<=innerHeight&&button.getBoundingClientRect().height>0)};})()`);
  check('residue dialog groups workspaces, blocked rows, trust entries and empty date directories', residueDialog.groups.length === 4 && residueDialog.checked.length === 6);
  check('only empty workspaces, trust entries and empty date directories are preselected', residueDialog.checked.filter(Boolean).length === 4 && residueDialog.checked[0] === true && residueDialog.checked[1] === false);
  check('the git repository row cannot be selected', residueDialog.disabled[2] === true && residueDialog.checked[2] === false);
  check('residue rows stay inside the dialog body', !residueDialog.bodyOverflows && residueDialog.insideModal);
  check('residue dialog footer stays inside the viewport', residueDialog.footerInViewport);
  await evaluate('Array.from(document.querySelectorAll(".ant-modal-footer button")).find(button=>button.textContent.includes("清理选中项")).click()');
  await waitFor('!!document.querySelector(".ant-modal-confirm")');
  const cleanConfirm = await evaluate('(()=>{const modal=document.querySelector(".ant-modal-confirm");return{title:modal.textContent.includes("确认清理残留"),content:modal.textContent.includes("1 个目录") && modal.textContent.includes("2 条信任配置"),footerInViewport:Array.from(modal.querySelectorAll(".ant-modal-footer button")).every(button=>button.getBoundingClientRect().bottom<=innerHeight)};})()');
  check('cleaning asks for confirmation with the selection summary', cleanConfirm.title && cleanConfirm.content);
  check('the cleanup confirmation footer stays inside the viewport', cleanConfirm.footerInViewport);
  await evaluate('Array.from(document.querySelectorAll(".ant-modal-confirm button")).find(button=>button.textContent.replace(/\\s/g,"")==="清理").click()');
  await waitFor('benchmark.metrics.requests.some(item=>item.command==="clean_codex_scratch_residue")');
  check('the cleanup sends the selected workspace, trust keys and date directories', await evaluate('(()=>{const request=benchmark.metrics.requests.filter(item=>item.command==="clean_codex_scratch_residue").at(-1);return request.args.workspacePaths.length===1 && request.args.trustKeys.length===2 && request.args.dateDirs.length===1;})()'));
  await waitFor('benchmark.metrics.requests.filter(item=>item.command==="scan_codex_scratch_residue").length===2');
  check('the dialog rescans after cleaning', await evaluate('benchmark.metrics.requests.filter(item=>item.command==="scan_codex_scratch_residue").length===2'));
  check('an emptied residue list shows the empty state', await waitFor('!!document.querySelector(".ant-empty")').then(()=>true).catch(()=>false));

  await writeFile(path.join(benchDirectory,'verification-results.json'),JSON.stringify(checks,null,2));
  return checks;
}
